# Kitty configuration file for a stylish and functional terminal
background_opacity 0.85
# Kitty Terminal Color Scheme

# Background and Foreground Colors
background #1d2021
foreground #d4be98

window_padding_width 0
single_window_padding_width -1
placement_strategy top-left

# Cursor Colors
cursor #d4be98
cursor_text_color #1d2021

# Colors for the 16 standard colors
color0  #1d2021   
color1  #e78a4e 
color2  #a9b665
color3  #ddc7a1
color4  #303536
color5  #7c6f64
color6  #434a4c
color7  #d4be98
color8  #3c3836
color9  #c14a4a
color10 #6c782e
color11 #ddc7a1
color12 #303536
color13 #c7ab7a
color14 #7c6f64
color15 #ffffff

font_size 17.0

# Remove fallback font guessing
fallback_family ""

# Add explicit symbol map for CJK characters only
symbol_map U+3000-U+30FF,U+4E00-U+9FFF,U+FF00-U+FFEF Noto Sans CJK JP
symbol_map U+3000-U+30FF,U+4E00-U+9FFF,U+FF00-U+FFEF IPAGothic


# BEGIN_KITTY_FONTS
font_family      family="Iosevka Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
